### ISSUE TITLE
4K屏幕下分辨率不正常

### ISSUE THREAD

**Issue by juebanlin** [istarmeow/Hackintosh-Dell.OptiPlex.7080-OpenCore.0.7.0-macOS.Big.Sur.11.4#1]
你好，请问你的是独显版本的7080mff吗？4K显示器只能显示2K，请问可以解决吗？

**Comment by istarmeow** [comment]
不是mff的，配置文件为集显，独显没资源测------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月24日(星期六) 下午4:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[istarmeow/Hackintosh-Dell.OptiPlex.7080-OpenCore.0.7.0-macOS.Big.Sur.11.4] 4K屏幕下分辨率不正常 (#1)

**Comment by juebanlin** [comment]
请问一个问题。同样的opencore 7.0版本,做好的EFI如果支持bigSur，然后这个EFI可以直接用在Catalina 15上吗(15需要的openvore版本是6.9)？如果不能是需要调整config.plist吗？

**Comment by istarmeow** [comment]
可能不支持，没验证过，只有做过升级的------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月24日(星期六) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [istarmeow/Hackintosh-Dell.OptiPlex.7080-OpenCore.0.7.0-macOS.Big.Sur.11.4] 4K屏幕下分辨率不正常 (#1)
